spring.application.name=donation
# Enable the H2 web console
spring.h2.console.enabled=true
# Set the URL path to access it
spring.h2.console.path=/h2-console
# Keep the database name consistent
spring.datasource.url=jdbc:h2:mem:testdb
